### PR TITLE
Triple rollout on 2021-07-14

### PR DESCRIPTION
**Pull request by sohankunkerkar**
- stable (34.20210626.3.1)
- testing(34.20210711.2.0)
- next (34.20210711.1.1)

### CODE REVIEW

**Comment by bgilbert** [comment]
```
[2021-07-14T22:11:27.715Z] next
[2021-07-14T22:11:27.715Z]     version: 34.20210711.1.1
[2021-07-14T22:11:27.715Z]     start: 2021-07-15 16:30:00+00:00 UTC (in 18:18:32)
[2021-07-14T22:11:27.715Z]            2021-07-15 12:30:00-04:00 Raleigh/New York/Toronto
[2021-07-14T22:11:27.715Z]            2021-07-15 18:30:00+02:00 Berlin/France/Poland
[2021-07-14T22:11:27.715Z]     duration: 2880m (48.0h)
[2021-07-14T22:11:27.715Z] stable
[2021-07-14T22:11:27.715Z]     version: 34.20210626.3.1
[2021-07-14T22:11:27.715Z]     start: 2021-07-15 16:30:00+00:00 UTC (in 18:18:32)
[2021-07-14T22:11:27.715Z]            2021-07-15 12:30:00-04:00 Raleigh/New York/Toronto
[2021-07-14T22:11:27.715Z]            2021-07-15 18:30:00+02:00 Berlin/France/Poland
[2021-07-14T22:11:27.715Z]     duration: 2880m (48.0h)
[2021-07-14T22:11:27.715Z] testing
[2021-07-14T22:11:27.715Z]     version: 34.20210711.2.0
[2021-07-14T22:11:27.715Z]     start: 2021-07-15 16:30:00+00:00 UTC (in 18:18:32)
[2021-07-14T22:11:27.715Z]            2021-07-15 12:30:00-04:00 Raleigh/New York/Toronto
[2021-07-14T22:11:27.715Z]            2021-07-15 18:30:00+02:00 Berlin/France/Poland
[2021-07-14T22:11:27.715Z]     duration: 2880m (48.0h)
```

**Review by bgilbert — APPROVED** [review]

**Comment by dustymabe** [comment]
Did we choose later in the day tomorrow versus earlier in the day for a reason? typically we'll get them started a few hours earlier in the day than they are currently scheduled for.

**Comment by sohankunkerkar** [comment]
> Did we choose later in the day tomorrow versus earlier in the day for a reason? typically we'll get them started a few hours earlier in the day than they are currently scheduled for.

There's no specific reason as such. I put up this PR today in the evening, so thought of leaving enough room for the review.

**Comment by bgilbert** [comment]
I think it's fine to start the rollout a bit later, but WFM either way.

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
