### PR TITLE
updates/{next,testing,stable}: drop unnecessary f36 barrier

### PR DESCRIPTION
**Pull request by jlebon**
We don't need two barriers here. It seems like there was confusion on this that lead us here. Let's clean that up.

### CODE REVIEW

**Comment by dustymabe** [comment]
I'm just not sure it's worth changing the graph now. Of course removing an extra update/boot is nice, but people that are starting older systems should probably just use the latest up front right?

The potential downside is undefined (unknown unknowns) where the potential upside is limited IMO.

**Comment by jlebon** [comment]
@lucab Do you see any potential issue with doing this cleanup?

> The potential downside is undefined (unknown unknowns)

Hmm, I'd rather do it and learn what breaks (and document it) than not do this now or ever in future cases like this. The stakes aren't very high IMO since as you said users should be using the latest upfront ideally.

**Comment by lucab** [comment]
@jlebon not really, I'd say this change should be safe and ok to merge.

**Comment by dustymabe** [comment]
I'm not worried about the mechanics of the zincati or coreos-cincinnati breaking (those are pretty rock solid). More about the new update path now breaking an assumption we had made or triggering some interaction in the software.

It's probably unlikely, but is it worth the risk of having to go back and investigate.

I'll approve the PR, just stating up front that I don't think it brings much value.

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
Ack, I see your perspective. From my POV, I don't think we should be afraid of doing this cleanup (and maybe break something), but I'm also OK not merging this. I guess this requires another stamp anyway, so if someone else weighs in we can get it in.

**Pull request closed without merging**
