### PR TITLE
ISSUE_TEMPLATE: stop manually checking for graduated overrides

### PR DESCRIPTION
**Pull request by jlebon**
This is automatically done now.

### CODE REVIEW

**Comment by jlebon** [comment]
Requires: https://github.com/coreos/fedora-coreos-config/pull/965

**Review by bgilbert — APPROVED** [review]
:tada:

**Comment by jlebon** [comment]
We can get this in now that [the GitHub Action is active](https://github.com/coreos/fedora-coreos-config/pull/1057)!

**Review by dustymabe — APPROVED** [review]
LGTM

**Pull request merged**
