### PR TITLE
release-prereqs.md: drop requirements no longer needed

### PR DESCRIPTION
**Pull request by dustymabe**
Over time we have automated some things so that we don't require as
many local git repos etc.. Let's update to the current requirements and
also update the current requirements to be a little more verbose/obvious.

### CODE REVIEW

**Comment by dustymabe** [comment]
@lucab @bgilbert @jlebon - can you sanity check me here?

**Review by jlebon — APPROVED** [review]
Nice, cool way to see the progress we've made!

**Comment by jlebon** [comment]
Maybe for the commit title something like: `release-prereqs.md: drop requirements no longer needed`?

**Comment by dustymabe** [comment]
> Maybe for the commit title something like: `release-prereqs.md: drop requirements no longer needed`?

updated

**Pull request merged**
