### PR TITLE
release-notes: updates for the 20240717 releases

### PR DESCRIPTION
**Pull request by marmijo**

### CODE REVIEW

**Review by aaradhak — DISMISSED** [review]
LGTM

**Review by travier — DISMISSED** [review]
LGTM

**Comment by travier** [comment]
After merging this, let's check the download page as we still don't have https://github.com/coreos/fedora-coreos-streams/issues/628 to validate this PR.

**Comment by aaradhak** [comment]
I am working on the CI check for the release-notes.

**Review by jlebon — APPROVED** [review]
Missing an entry for https://github.com/coreos/fedora-coreos-tracker/issues/1758 for all three (we fast-tracked the fix to stable). Otherwise LGTM!

**Comment by marmijo** [comment]
Good catch! I just amended the commit to include it.

**Review by travier — APPROVED** [review]

**Review by aaradhak — APPROVED** [review]

**Pull request merged**
