### PR TITLE
rollouts: stable and testing, 2020-04-08

### PR DESCRIPTION
**Pull request by lucab**
This contains two rollouts:
 * stable, 31.20200323.3.2
 * testing, 31.20200407.2.2

### CODE REVIEW

**Comment by dustymabe** [comment]
LGTM

```
$ date -d @1586442600
Thu 09 Apr 2020 10:30:00 AM EDT
```

**Comment by jlebon** [comment]
Yup, LGTM!

And now that CI prints the rollout, it's easier to review start dates and durations:

```
+ make print-rollouts
stable rollout of 31.20200323.3.2 scheduled for 2020-04-09 14:30:00 UTC for 2880m (48.0h)
testing rollout of 31.20200407.2.2 scheduled for 2020-04-09 14:30:00 UTC for 2880m (48.0h)
```

**Comment by dustymabe** [comment]
haha - it's still another conversion for me from UTC to my local time so I just stick with running the `date command` anyway

**Pull request merged**
