### PR TITLE
add barrier for 39.20240104.3.0; update release notes

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Review by marmijo — DISMISSED** [review]

**Review by jlebon — DISMISSED** [review]
Should we mention that we're publishing to a new AWS region? (`ca-west-1`).

**Comment by dustymabe** [comment]
> Should we mention that we're publishing to a new AWS region? (`ca-west-1`).

probably - I guess the reason we haven't in the past is because of the paperwork required.

**Comment by dustymabe** [comment]
updated^^

**Review by jlebon — APPROVED** [review]

**Review by marmijo — APPROVED** [review]
LGTM

**Pull request merged**
