### PR TITLE
*/testing: update to 30.20191014.1

### PR DESCRIPTION
**Pull request by jlebon**
Note this is a barrier update due to:
https://github.com/coreos/fedora-coreos-streams/issues/26#issuecomment-558361931

### CODE REVIEW

**Comment by dustymabe** [comment]
> Note this is a barrier update due to:

I think Luca mentioned that we shouldn't have this be a barrier and rollout at the same time. i.e. we should treat this like a normal update for now until rollout percentage==100 and then we can add barrier later.

**Comment by jlebon** [comment]
Hmm, I took [this comment](https://github.com/coreos/fedora-coreos-streams/issues/26#issuecomment-559124876) to mean this should work now. But anyway, yeah we can just start the rollout now and add it later too to be safe.

**Comment by jlebon** [comment]
OK, updated! I also bumped the rollout another hour.
I set the duration to just 12h since this should be a pretty safe update. We can then start the next release tomorrow morning.

**Comment by dustymabe** [comment]
> Hmm, I took [this comment](https://github.com/coreos/fedora-coreos-streams/issues/26#issuecomment-559124876) to mean this should work now. But anyway, yeah we can just start the rollout now and add it later too to be safe.

+1 - I had missed that comment since I've been in-and-out today. Sorry about the noise

**Comment by lucab** [comment]
@jlebon is correct, the barrier+rollout combo ("rolling barrier") should have worked too.

Sidenote: the rollout duration is 20 hours (1200 mins), not 12. At the time of this writing, it is at ~70%. It will reach 100% at 15:00 UTC.

**Pull request merged**
