### PR TITLE
Roll out stable 35.20220424.3.0, roll out next 36.20220507.1.0 and roll out testing 36.20220505.2.0

### PR DESCRIPTION
**Pull request by ravanelli**

### CODE REVIEW

**Review by bgilbert — APPROVED** [review]
LGTM

**Review by dustymabe — CHANGES_REQUESTED** [review]
hold

**Review by dustymabe — APPROVED** [review]
LGTM

**Review by bgilbert — CHANGES_REQUESTED** [review]
hold

**Review by bgilbert — APPROVED** [review]
LGTM

**Pull request merged**
