### PR TITLE
Stream metadata for testing release 30.20190716.0

### PR DESCRIPTION
**Pull request by sinnykumari**

### CODE REVIEW

**Comment by jlebon** [comment]
Note we'll need at least one other build for https://github.com/coreos/coreos-assembler/pull/616.

**Comment by sinnykumari** [comment]
I was wondering, should we switch PR merge default to `Rebase and Merge`? I kind of like clean git commit history but best would be decide collectively.

**Comment by jlebon** [comment]
> I was wondering, should we switch PR merge default to `Rebase and Merge`?

I prefer it as well, though whoever set up this repo (/cc @bgilbert ?) doesn't. :)

**Comment by jlebon** [comment]
Latest `testing` release is out. Let's update this for `30.20190716.0` ?

**Comment by bgilbert** [comment]
@sinnykumari @jlebon I think rebase-and-merge makes sense with this repo, since it'll be a stream of single, mostly-automated commits.  Changed.

**Comment by sinnykumari** [comment]
Updated it with 30.20190716.0 !

**Pull request merged**
