### PR TITLE
templates: several updates

### PR DESCRIPTION
**Pull request by bgilbert**
For convenience, we'd like all streams to be updated in the same PR.  (Also, there will be merge conflicts if a second PR is created before the first one merges.)  Add a sync step to make this explicit.

### CODE REVIEW

**Review by lucab — DISMISSED** [review]

**Comment by dustymabe** [comment]
I wonder if we should add some wording about this being optional. i.e. if for some reason one of the releases is delayed a few days I wouldn't want to hold the other two.

**Comment by bgilbert** [comment]
Updated, and a few more fixes added.

**Review by jlebon — APPROVED** [review]

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by sohankunkerkar** [comment]
Can you also add a text to explain a bit more about the `aarch64` Jenkins build?
Like something along the similar line : `Don't trigger a manual build for aarch64, it will be run automatically as part of the x-86 build`

**Comment by bgilbert** [comment]
@sohankunkerkar I'll save that for a followup.  The configuration of this repo has been changed so a force-push would invalidate the existing approvals.

**Comment by bgilbert** [comment]
Followup in https://github.com/coreos/fedora-coreos-streams/pull/411.

**Pull request merged**
