### PR TITLE
rollout.py: Update location information

### PR DESCRIPTION
**Pull request by c4rt0**
Update location information; include time zones for all team members working on releases.

### CODE REVIEW

**Review by jlebon — COMMENTED** [review]
Really, this list is intended to represent the location of people involved in the release process. E.g. feel free to add Ireland to the list if you'd like (though looking it up, I guess that's UTC, which is already covered). Conversely, I don't think we have anyone in Germany involved in the release process anymore so we could also just drop that reference.

But we should probably add Vancouver, Colorado, and Brazil.

**Comment by c4rt0** [comment]
> Really, this list is intended to represent the location of people involved in the release process. E.g. feel free to add Ireland to the list if you'd like (though looking it up, I guess that's UTC, which is already covered). Conversely, I don't think we have anyone in Germany involved in the release process anymore so we could also just drop that reference.
> 
> But we should probably add Vancouver, Colorado, and Brazil.

Thanks for the explanation, I didn't catch for whom this was intended. 
Since Germany is under one and the very same time zone as France and Poland I will still leave it in... we have folks who might do some work on releases in the future.
Ireland is in a different time zone. I will add it with the locations suggested above in the next push.

**Comment by c4rt0** [comment]
> Really, this list is intended to represent the location of people involved in the release process. E.g. feel free to add Ireland to the list if you'd like (though looking it up, I guess that's UTC, which is already covered). Conversely, I don't think we have anyone in Germany involved in the release process anymore so we could also just drop that reference.
> 
> But we should probably add Vancouver, Colorado, and Brazil.

Thanks for the explanation, I didn't catch for whom this was intended. 
Since Germany is under one and the very same time zone as France and Poland I will still leave it in... we have folks in there who might do some work on releases in the future.
Ireland is in a different time zone. I will add it with the locations suggested above in the next push.

**Review by jlebon — APPROVED** [review]
A bit longer than I thought (I guess we don't have many people sharing time zones) but meh, cool with it. Thanks!

**Review by dustymabe — APPROVED** [review]

**Pull request merged**
