### PR TITLE
templates: Link to stream download page & graph viewer

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Review by jlebon — APPROVED** [review]
LGTM, though deferring to @lucab in case there are unknowns re. that graph.

**Comment by lucab** [comment]
The graph viewer is really a mock/unfinished page. I wasn't planning to link it anywhere until somebody with proper HTML/JS skills goes over it, but if people are finding it useful...

**Comment by travier** [comment]
I find it really useful to visualize the graph and a better UX than curling and manual checking during releases. It's only linked here for development and not on the main page.

**Comment by jlebon** [comment]
I do like it as well. Let's try it and we can always back it out if e.g. it stops rendering properly.

**Pull request merged**
